name: Build and Deploy

on:
  push:	
    branches:	
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.x]
        
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: master # The branch the action should deploy to.
        FOLDER: example # The folder the action should deploy.

    - name: Install Packages
      working-directory: ./example
      run: npm install
      
    - name: Deploy to GH Pages
      working-directory: ./example
      run: npm run deploy
    
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Add changes" -a
      
    - name: Updating Domain
      run: echo "Update domain"

