name: Build and Deploy

on:
  push:	
    branches:	
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: master # The branch the action should deploy to.
        FOLDER: example # The folder the action should deploy.

    - name: Install Packages
      working-directory: ./example
      run: npm install
      
    - name: Deploy to GH Pages
      working-directory: ./example
      run: |
        git config --global user.email "kaanse@hotmail.com"
        git config --global user.name "kaansey"
        npm run deploy
      
    - name: Updating Domain
      run: echo "Update domain"
      
