name: Build and Deploy

on:
  push:	
    branches:	
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: master # The branch the action should deploy to.
        FOLDER: example # The folder the action should deploy.
    - name: Install Packages
      run: npm run predeploy
    - name: Deploy to GH Pages
      run: npm run deploy
    - name: Updating Domain
      run: echo "Update domain"
      
